`timescale 1ns/1ps
`include "cnn_ddr_defs.svh"

// ============================================================================
// Simulation testbench for kv260_cnn_smoke_top_vgg16_like_32_p128
//
// Purpose:
//   - Instantiate the exact KV260 smoke top used for board bring-up.
//   - Model the external AXI DDR as a word-addressable memory behind AXI4.
//   - Preload the same IFM/weight hex files used by the KV260 XSCT flow.
//   - Compare the final OFM DDR region against the packed golden hex.
//
// Default input files are the paths generated by run_vgg16_like_32_p128_flow.ps1:
//   eval/assets/vgg16_like_32_p128/inputs/img0000/ifm_ddr_cnnv4.hex
//   eval/assets/vgg16_like_32_p128/weights/all_weights_cnnv4.hex
//   eval/golden/vgg16_like_32_p128/img0000/expected_final_ofm_cnnv4.hex
//   eval/golden/vgg16_like_32_p128/img0000/expected_ofm_words.txt
//
// Normal no-plusarg version:
 //   - File paths are hard-coded below.
 //   - MAX_CYCLES is a localparam.
 //   - Strict AXI mode: direct/debug DDR writes are monitored but NOT mirrored into DDR.
 //   - DDR model is updated only by AXI AW/W/B transactions.
// ============================================================================

module tb_kv260_cnn_smoke_top_vgg16_like_32_p128_axi_expected_compare;

  localparam int DATA_W         = 8;
  localparam int PSUM_W         = 32;
  localparam int PTOTAL         = 128;
  localparam int PV_MAX         = 8;
  localparam int PF_MAX         = 16;
  localparam int PC_MODE2       = 8;
  localparam int PF_MODE2       = 16;
  localparam int C_MAX          = 64;
  localparam int F_MAX          = 64;
  localparam int W_MAX          = 32;
  localparam int H_MAX          = 32;
  localparam int HT             = 4;
  localparam int K_MAX          = 3;
  localparam int OFM_ROW_STRIDE = 4;
  localparam int WGT_DEPTH      = 512;
  localparam int OFM_BANK_DEPTH = H_MAX * OFM_ROW_STRIDE;
  localparam int OFM_LINEAR_DEPTH = F_MAX * OFM_BANK_DEPTH;
  localparam int CFG_DEPTH      = 16;

  localparam int DDR_ADDR_W     = `CNN_DDR_ADDR_W;
  localparam int DDR_WORD_W     = PV_MAX * DATA_W;   // 64 bits
  localparam int DDR_WORD_BYTES = DDR_WORD_W / 8;     // 8 bytes
  localparam int AXI_ADDR_W     = 40;
  localparam int AXI_DATA_W     = DDR_WORD_W;
  localparam int AXI_ID_W       = 1;
  localparam logic [AXI_ADDR_W-1:0] AXI_DDR_BASE_ADDR = 40'h0000_7000_0000;
  localparam int WR_FIFO_DEPTH  = 128;
  localparam int MAX_CYCLES     = 20_000_000;

  localparam int DDR_DEPTH      = `CNN_DDR_DEPTH;
  localparam int OFM_MAX_WORDS  = `DDR_OFM_SIZE;

  // --------------------------------------------------------------------------
  // Clock/reset/run.
  // --------------------------------------------------------------------------
  logic clk;
  logic rst_n;
  logic soft_reset_n;
  logic run;
  logic abort;

  initial clk = 1'b0;
  always #5 clk = ~clk;  // 100 MHz simulation clock

  // --------------------------------------------------------------------------
  // DUT status/debug.
  // --------------------------------------------------------------------------
  logic cfg_done;
  logic start_pulse;
  logic busy;
  logic done;
  logic error;
  logic core_busy;
  logic core_done;
  logic core_error;
  logic bridge_busy;
  logic bridge_error;
  logic wr_fifo_overflow;
  logic [$clog2(CFG_DEPTH)-1:0] dbg_layer_idx;
  logic dbg_mode;
  logic dbg_weight_bank;
  logic [3:0] dbg_error_vec;

  logic dbg_ddr_rd_req;
  logic [DDR_ADDR_W-1:0] dbg_ddr_rd_addr;
  logic dbg_ddr_rd_valid;
  logic [DDR_WORD_W-1:0] dbg_ddr_rd_data;
  logic dbg_ddr_wr_en;
  logic [DDR_ADDR_W-1:0] dbg_ddr_wr_addr;
  logic [DDR_WORD_W-1:0] dbg_ddr_wr_data;
  logic [(DDR_WORD_W/8)-1:0] dbg_ddr_wr_be;

  // --------------------------------------------------------------------------
  // AXI wires between smoke top and DDR model.
  // --------------------------------------------------------------------------
  logic [AXI_ID_W-1:0]   m_axi_awid;
  logic [AXI_ADDR_W-1:0] m_axi_awaddr;
  logic [7:0]            m_axi_awlen;
  logic [2:0]            m_axi_awsize;
  logic [1:0]            m_axi_awburst;
  logic                  m_axi_awlock;
  logic [3:0]            m_axi_awcache;
  logic [2:0]            m_axi_awprot;
  logic [3:0]            m_axi_awqos;
  logic [3:0]            m_axi_awregion;
  logic                  m_axi_awvalid;
  logic                  m_axi_awready;

  logic [AXI_DATA_W-1:0] m_axi_wdata;
  logic [(AXI_DATA_W/8)-1:0] m_axi_wstrb;
  logic                  m_axi_wlast;
  logic                  m_axi_wvalid;
  logic                  m_axi_wready;

  logic [AXI_ID_W-1:0]   m_axi_bid;
  logic [1:0]            m_axi_bresp;
  logic                  m_axi_bvalid;
  logic                  m_axi_bready;

  logic [AXI_ID_W-1:0]   m_axi_arid;
  logic [AXI_ADDR_W-1:0] m_axi_araddr;
  logic [7:0]            m_axi_arlen;
  logic [2:0]            m_axi_arsize;
  logic [1:0]            m_axi_arburst;
  logic                  m_axi_arlock;
  logic [3:0]            m_axi_arcache;
  logic [2:0]            m_axi_arprot;
  logic [3:0]            m_axi_arqos;
  logic [3:0]            m_axi_arregion;
  logic                  m_axi_arvalid;
  logic                  m_axi_arready;

  logic [AXI_ID_W-1:0]   m_axi_rid;
  logic [AXI_DATA_W-1:0] m_axi_rdata;
  logic [1:0]            m_axi_rresp;
  logic                  m_axi_rlast;
  logic                  m_axi_rvalid;
  logic                  m_axi_rready;

  // --------------------------------------------------------------------------
  // DUT: exact board smoke top.
  // --------------------------------------------------------------------------
  kv260_cnn_smoke_top_vgg16_like_32_p128 #(
    .DATA_W(DATA_W),
    .PSUM_W(PSUM_W),
    .PTOTAL(PTOTAL),
    .PV_MAX(PV_MAX),
    .PF_MAX(PF_MAX),
    .PC_MODE2(PC_MODE2),
    .PF_MODE2(PF_MODE2),
    .C_MAX(C_MAX),
    .F_MAX(F_MAX),
    .W_MAX(W_MAX),
    .H_MAX(H_MAX),
    .HT(HT),
    .K_MAX(K_MAX),
    .OFM_ROW_STRIDE(OFM_ROW_STRIDE),
    .WGT_DEPTH(WGT_DEPTH),
    .OFM_BANK_DEPTH(OFM_BANK_DEPTH),
    .OFM_LINEAR_DEPTH(OFM_LINEAR_DEPTH),
    .CFG_DEPTH(CFG_DEPTH),
    .DDR_ADDR_W(DDR_ADDR_W),
    .DDR_WORD_W(DDR_WORD_W),
    .AXI_ADDR_W(AXI_ADDR_W),
    .AXI_DATA_W(AXI_DATA_W),
    .AXI_ID_W(AXI_ID_W),
    .AXI_DDR_BASE_ADDR(AXI_DDR_BASE_ADDR),
    .WR_FIFO_DEPTH(WR_FIFO_DEPTH)
  ) dut (
    .clk(clk),
    .rst_n(rst_n),
    .soft_reset_n(soft_reset_n),
    .run(run),
    .abort(abort),
    .cfg_done(cfg_done),
    .start_pulse(start_pulse),
    .busy(busy),
    .done(done),
    .error(error),
    .core_busy(core_busy),
    .core_done(core_done),
    .core_error(core_error),
    .bridge_busy(bridge_busy),
    .bridge_error(bridge_error),
    .wr_fifo_overflow(wr_fifo_overflow),
    .dbg_layer_idx(dbg_layer_idx),
    .dbg_mode(dbg_mode),
    .dbg_weight_bank(dbg_weight_bank),
    .dbg_error_vec(dbg_error_vec),
    .dbg_ddr_rd_req(dbg_ddr_rd_req),
    .dbg_ddr_rd_addr(dbg_ddr_rd_addr),
    .dbg_ddr_rd_valid(dbg_ddr_rd_valid),
    .dbg_ddr_rd_data(dbg_ddr_rd_data),
    .dbg_ddr_wr_en(dbg_ddr_wr_en),
    .dbg_ddr_wr_addr(dbg_ddr_wr_addr),
    .dbg_ddr_wr_data(dbg_ddr_wr_data),
    .dbg_ddr_wr_be(dbg_ddr_wr_be),
    .m_axi_awid(m_axi_awid),
    .m_axi_awaddr(m_axi_awaddr),
    .m_axi_awlen(m_axi_awlen),
    .m_axi_awsize(m_axi_awsize),
    .m_axi_awburst(m_axi_awburst),
    .m_axi_awlock(m_axi_awlock),
    .m_axi_awcache(m_axi_awcache),
    .m_axi_awprot(m_axi_awprot),
    .m_axi_awqos(m_axi_awqos),
    .m_axi_awregion(m_axi_awregion),
    .m_axi_awvalid(m_axi_awvalid),
    .m_axi_awready(m_axi_awready),
    .m_axi_wdata(m_axi_wdata),
    .m_axi_wstrb(m_axi_wstrb),
    .m_axi_wlast(m_axi_wlast),
    .m_axi_wvalid(m_axi_wvalid),
    .m_axi_wready(m_axi_wready),
    .m_axi_bid(m_axi_bid),
    .m_axi_bresp(m_axi_bresp),
    .m_axi_bvalid(m_axi_bvalid),
    .m_axi_bready(m_axi_bready),
    .m_axi_arid(m_axi_arid),
    .m_axi_araddr(m_axi_araddr),
    .m_axi_arlen(m_axi_arlen),
    .m_axi_arsize(m_axi_arsize),
    .m_axi_arburst(m_axi_arburst),
    .m_axi_arlock(m_axi_arlock),
    .m_axi_arcache(m_axi_arcache),
    .m_axi_arprot(m_axi_arprot),
    .m_axi_arqos(m_axi_arqos),
    .m_axi_arregion(m_axi_arregion),
    .m_axi_arvalid(m_axi_arvalid),
    .m_axi_arready(m_axi_arready),
    .m_axi_rid(m_axi_rid),
    .m_axi_rdata(m_axi_rdata),
    .m_axi_rresp(m_axi_rresp),
    .m_axi_rlast(m_axi_rlast),
    .m_axi_rvalid(m_axi_rvalid),
    .m_axi_rready(m_axi_rready)
  );

  // --------------------------------------------------------------------------
  // AXI DDR model.
  // DDR address unit in CNN RTL = 64-bit word. AXI address unit = byte.
  // --------------------------------------------------------------------------
  logic [DDR_WORD_W-1:0] ddr_mem [0:DDR_DEPTH-1];
  logic [DDR_WORD_W-1:0] exp_mem [0:OFM_MAX_WORDS-1];

  // Diagnostics. These are hard-coded; no plusargs/macros are required.
  longint unsigned axi_aw_count;
  longint unsigned axi_w_count;
  longint unsigned axi_b_count;
  longint unsigned axi_ar_count;
  longint unsigned axi_r_count;
  longint unsigned axi_write_count;
  longint unsigned axi_ofm_write_count;
  int unsigned     axi_first_ofm_wr_idx;
  int unsigned     axi_last_ofm_wr_idx;

  longint unsigned dbg_write_count;
  longint unsigned dbg_ofm_write_count;
  int unsigned     dbg_first_wr_idx;
  int unsigned     dbg_last_wr_idx;
  int unsigned     dbg_first_ofm_wr_idx;
  int unsigned     dbg_last_ofm_wr_idx;
  logic [DDR_ADDR_W-1:0]  dbg_sample_addr [0:15];
  logic [DDR_WORD_W-1:0]  dbg_sample_data [0:15];
  logic [(DDR_WORD_W/8)-1:0] dbg_sample_be [0:15];
  int unsigned            dbg_sample_count;

  longint unsigned bridge_in_write_count;
  int unsigned     bridge_in_first_wr_idx;
  int unsigned     bridge_in_last_wr_idx;
  logic [DDR_ADDR_W-1:0]  bridge_in_sample_addr [0:15];
  logic [DDR_WORD_W-1:0]  bridge_in_sample_data [0:15];
  logic [(DDR_WORD_W/8)-1:0] bridge_in_sample_be [0:15];
  int unsigned            bridge_in_sample_count;

  function automatic int unsigned axi_to_word_idx(input logic [AXI_ADDR_W-1:0] byte_addr);
    logic [AXI_ADDR_W-1:0] off;
    begin
      if (byte_addr < AXI_DDR_BASE_ADDR) begin
        axi_to_word_idx = '1;
      end else begin
        off = byte_addr - AXI_DDR_BASE_ADDR;
        axi_to_word_idx = int'(off >> $clog2(DDR_WORD_BYTES));
      end
    end
  endfunction

  task automatic axi_mem_write_word(
    input logic [AXI_ADDR_W-1:0] byte_addr,
    input logic [AXI_DATA_W-1:0] data,
    input logic [(AXI_DATA_W/8)-1:0] strb
  );
    int unsigned idx;
    begin
      idx = axi_to_word_idx(byte_addr);
      if (idx >= DDR_DEPTH) begin
        $fatal(1, "AXI write address out of range: byte_addr=0x%0h idx=%0d", byte_addr, idx);
      end
      for (int b = 0; b < DDR_WORD_BYTES; b++) begin
        if (strb[b]) begin
          ddr_mem[idx][b*8 +: 8] = data[b*8 +: 8];
        end
      end
    end
  endtask

  function automatic logic [AXI_DATA_W-1:0] axi_mem_read_word(input logic [AXI_ADDR_W-1:0] byte_addr);
    int unsigned idx;
    begin
      idx = axi_to_word_idx(byte_addr);
      if (idx >= DDR_DEPTH) begin
        $fatal(1, "AXI read address out of range: byte_addr=0x%0h idx=%0d", byte_addr, idx);
      end
      axi_mem_read_word = ddr_mem[idx];
    end
  endfunction

  // AXI write channel state. This model supports incrementing bursts but is
  // intentionally permissive; it is enough for cnn_dma_to_axi_bridge_kv260.
  logic wr_active_q;
  logic [AXI_ADDR_W-1:0] wr_addr_q;
  logic [7:0] wr_left_q;
  logic [AXI_ID_W-1:0] wr_id_q;

  assign m_axi_awready = !wr_active_q;
  assign m_axi_wready  = wr_active_q || (m_axi_awvalid && m_axi_awready);

  always @(posedge clk) begin
    if (!rst_n) begin
      wr_active_q  <= 1'b0;
      wr_addr_q    <= '0;
      wr_left_q    <= '0;
      wr_id_q      <= '0;
      m_axi_bvalid <= 1'b0;
      m_axi_bresp  <= 2'b00;
      m_axi_bid    <= '0;
      axi_aw_count <= 0;
      axi_w_count  <= 0;
      axi_b_count  <= 0;
      axi_write_count <= 0;
      axi_ofm_write_count <= 0;
      axi_first_ofm_wr_idx <= 0;
      axi_last_ofm_wr_idx  <= 0;
    end else begin
      logic aw_hs;
      logic w_hs;
      logic [AXI_ADDR_W-1:0] use_addr;
      logic [7:0] use_left;
      logic [AXI_ID_W-1:0] use_id;
      aw_hs = m_axi_awvalid && m_axi_awready;
      w_hs  = m_axi_wvalid  && m_axi_wready;

      if (m_axi_bvalid && m_axi_bready) begin
        m_axi_bvalid <= 1'b0;
        axi_b_count <= axi_b_count + 1;
      end

      if (aw_hs) begin
        axi_aw_count <= axi_aw_count + 1;
        wr_active_q <= 1'b1;
        wr_addr_q   <= m_axi_awaddr;
        wr_left_q   <= m_axi_awlen;
        wr_id_q     <= m_axi_awid;
      end

      if (w_hs) begin
        use_addr = aw_hs ? m_axi_awaddr : wr_addr_q;
        use_left = aw_hs ? m_axi_awlen  : wr_left_q;
        use_id   = aw_hs ? m_axi_awid   : wr_id_q;

        axi_w_count <= axi_w_count + 1;
        axi_mem_write_word(use_addr, m_axi_wdata, m_axi_wstrb);
        begin
          int unsigned axi_wr_word_idx;
          axi_wr_word_idx = axi_to_word_idx(use_addr);
          axi_write_count <= axi_write_count + 1;
          if ((axi_wr_word_idx >= `DDR_OFM_BASE) &&
              (axi_wr_word_idx < (`DDR_OFM_BASE + `DDR_OFM_SIZE))) begin
            if (axi_ofm_write_count == 0) axi_first_ofm_wr_idx <= axi_wr_word_idx;
            axi_last_ofm_wr_idx <= axi_wr_word_idx;
            axi_ofm_write_count <= axi_ofm_write_count + 1;
          end
        end

        if (m_axi_wlast || (use_left == 8'd0)) begin
          wr_active_q  <= 1'b0;
          m_axi_bvalid <= 1'b1;
          m_axi_bresp  <= 2'b00;
          m_axi_bid    <= use_id;
        end else begin
          wr_active_q <= 1'b1;
          wr_addr_q   <= use_addr + DDR_WORD_BYTES;
          wr_left_q   <= use_left - 8'd1;
          wr_id_q     <= use_id;
        end
      end
    end
  end

  // AXI read channel state.
  logic rd_active_q;
  logic [AXI_ADDR_W-1:0] rd_addr_q;
  logic [7:0] rd_left_q;
  logic [AXI_ID_W-1:0] rd_id_q;

  assign m_axi_arready = !rd_active_q && !(m_axi_rvalid && !m_axi_rready);

  always @(posedge clk) begin
    if (!rst_n) begin
      rd_active_q  <= 1'b0;
      rd_addr_q    <= '0;
      rd_left_q    <= '0;
      rd_id_q      <= '0;
      m_axi_rvalid <= 1'b0;
      m_axi_rdata  <= '0;
      m_axi_rresp  <= 2'b00;
      m_axi_rlast  <= 1'b0;
      m_axi_rid    <= '0;
      axi_ar_count <= 0;
      axi_r_count  <= 0;
    end else begin
      logic ar_hs;
      logic can_drive_r;
      logic [AXI_ADDR_W-1:0] use_addr;
      logic [7:0] use_left;
      logic [AXI_ID_W-1:0] use_id;

      ar_hs       = m_axi_arvalid && m_axi_arready;
      can_drive_r = (!m_axi_rvalid) || m_axi_rready;

      if (ar_hs) begin
        axi_ar_count <= axi_ar_count + 1;
        rd_active_q <= 1'b1;
        rd_addr_q   <= m_axi_araddr;
        rd_left_q   <= m_axi_arlen;
        rd_id_q     <= m_axi_arid;
      end

      if (can_drive_r) begin
        if (rd_active_q || ar_hs) begin
          use_addr = ar_hs ? m_axi_araddr : rd_addr_q;
          use_left = ar_hs ? m_axi_arlen  : rd_left_q;
          use_id   = ar_hs ? m_axi_arid   : rd_id_q;

          m_axi_rvalid <= 1'b1;
          m_axi_rdata  <= axi_mem_read_word(use_addr);
          if (m_axi_rready || !m_axi_rvalid) begin
            axi_r_count <= axi_r_count + 1;
          end
          m_axi_rresp  <= 2'b00;
          m_axi_rlast  <= (use_left == 8'd0);
          m_axi_rid    <= use_id;

          if (use_left == 8'd0) begin
            rd_active_q <= 1'b0;
          end else begin
            rd_active_q <= 1'b1;
            rd_addr_q   <= use_addr + DDR_WORD_BYTES;
            rd_left_q   <= use_left - 8'd1;
            rd_id_q     <= use_id;
          end
        end else begin
          m_axi_rvalid <= 1'b0;
          m_axi_rlast  <= 1'b0;
        end
      end
    end
  end

  // Direct/debug write monitor only. Strict AXI mode does NOT mirror these writes
  // into ddr_mem; only AXI AW/W updates the DDR model.
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dbg_write_count <= 0;
      dbg_ofm_write_count <= 0;
      dbg_first_wr_idx <= 0;
      dbg_last_wr_idx <= 0;
      dbg_first_ofm_wr_idx <= 0;
      dbg_last_ofm_wr_idx <= 0;
      dbg_sample_count <= 0;
    end else if (dbg_ddr_wr_en) begin
      if (dbg_write_count == 0) dbg_first_wr_idx <= dbg_ddr_wr_addr;
      dbg_last_wr_idx <= dbg_ddr_wr_addr;
      dbg_write_count <= dbg_write_count + 1;

      if (dbg_sample_count < 16) begin
        dbg_sample_addr[dbg_sample_count] <= dbg_ddr_wr_addr;
        dbg_sample_data[dbg_sample_count] <= dbg_ddr_wr_data;
        dbg_sample_be[dbg_sample_count]   <= dbg_ddr_wr_be;
        dbg_sample_count <= dbg_sample_count + 1;
      end

      if ((dbg_ddr_wr_addr >= `DDR_OFM_BASE) &&
          (dbg_ddr_wr_addr < (`DDR_OFM_BASE + `DDR_OFM_SIZE))) begin
        if (dbg_ofm_write_count == 0) dbg_first_ofm_wr_idx <= dbg_ddr_wr_addr;
        dbg_last_ofm_wr_idx <= dbg_ddr_wr_addr;
        dbg_ofm_write_count <= dbg_ofm_write_count + 1;
      end
    end
  end

  // Probe the real bridge input. If DBG writes exist but BRIDGE_IN stays zero,
  // the smoke top is not routing core direct writes into the bridge input.
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      bridge_in_write_count <= 0;
      bridge_in_first_wr_idx <= 0;
      bridge_in_last_wr_idx <= 0;
      bridge_in_sample_count <= 0;
    end else if (dut.u_top.u_dma_to_axi_bridge.ddr_wr_en) begin
      if (bridge_in_write_count == 0) bridge_in_first_wr_idx <= dut.u_top.u_dma_to_axi_bridge.ddr_wr_addr;
      bridge_in_last_wr_idx <= dut.u_top.u_dma_to_axi_bridge.ddr_wr_addr;
      bridge_in_write_count <= bridge_in_write_count + 1;

      if (bridge_in_sample_count < 16) begin
        bridge_in_sample_addr[bridge_in_sample_count] <= dut.u_top.u_dma_to_axi_bridge.ddr_wr_addr;
        bridge_in_sample_data[bridge_in_sample_count] <= dut.u_top.u_dma_to_axi_bridge.ddr_wr_data;
        bridge_in_sample_be[bridge_in_sample_count]   <= dut.u_top.u_dma_to_axi_bridge.ddr_wr_be;
        bridge_in_sample_count <= bridge_in_sample_count + 1;
      end
    end
  end

  // --------------------------------------------------------------------------
  // File handling helpers.
  // --------------------------------------------------------------------------
  function automatic int file_exists(input string path);
    int fd;
    begin
      fd = $fopen(path, "r");
      if (fd != 0) begin
        $fclose(fd);
        file_exists = 1;
      end else begin
        file_exists = 0;
      end
    end
  endfunction

  function automatic int count_hex_lines(input string path);
    int fd;
    int count;
    string line;
    begin
      count = 0;
      fd = $fopen(path, "r");
      if (fd == 0) begin
        count_hex_lines = 0;
      end else begin
        while ($fgets(line, fd)) begin
          // Count all non-empty-ish lines. Packed hex files generated by the
          // flow have one word per line and no comments.
          if (line.len() > 0) count++;
        end
        $fclose(fd);
        count_hex_lines = count;
      end
    end
  endfunction

  task automatic read_expected_word_count(
    input  string count_path,
    input  string exp_hex_path,
    output int expected_words
  );
    int fd;
    int code;
    begin
      expected_words = 0;
      fd = $fopen(count_path, "r");
      if (fd != 0) begin
        code = $fscanf(fd, "%d", expected_words);
        $fclose(fd);
        if (code != 1) expected_words = 0;
      end
      if (expected_words <= 0) begin
        expected_words = count_hex_lines(exp_hex_path);
      end

      if (expected_words <= 0 || expected_words > OFM_MAX_WORDS) begin
        $fatal(1, "Invalid expected word count %0d. Check %s", expected_words, count_path);
      end
    end
  endtask

  // --------------------------------------------------------------------------
  // Test sequence.
  // --------------------------------------------------------------------------
  string ifm_hex_path;
  string wgt_hex_path;
  string exp_hex_path;
  string exp_words_path;
  string out_hex_path;
  int expected_words;
  int mismatch_count;
  int out_fd;

  initial begin : TB_MAIN
    // Defaults match the generated package location used by the KV260 flow.
    // Use forward slashes so XSim can open the files on Windows.
    ifm_hex_path       = "D:/sdh/CNN_V4/vgg16_like_32_p128_kv260_package/eval/assets/vgg16_like_32_p128/inputs/img0000/ifm_ddr_cnnv4.hex";
    wgt_hex_path       = "D:/sdh/CNN_V4/vgg16_like_32_p128_kv260_package/eval/assets/vgg16_like_32_p128/weights/all_weights_cnnv4.hex";
    exp_hex_path       = "D:/sdh/CNN_V4/vgg16_like_32_p128_kv260_package/eval/golden/vgg16_like_32_p128/img0000/expected_final_ofm_cnnv4.hex";
    exp_words_path     = "D:/sdh/CNN_V4/vgg16_like_32_p128_kv260_package/eval/golden/vgg16_like_32_p128/img0000/expected_ofm_words.txt";
    out_hex_path       = "fpga_ofm_readback_sim_axi_strict.hex";

    if (!file_exists(ifm_hex_path)) begin
      $fatal(1, "IFM hex not found: %s. Run run_vgg16_like_32_p128_flow.ps1 first", ifm_hex_path);
    end
    if (!file_exists(wgt_hex_path)) begin
      $fatal(1, "Weight hex not found: %s. Run run_vgg16_like_32_p128_flow.ps1 first", wgt_hex_path);
    end
    if (!file_exists(exp_hex_path)) begin
      $fatal(1, "Expected OFM hex not found: %s. Run run_vgg16_like_32_p128_flow.ps1 first", exp_hex_path);
    end

    read_expected_word_count(exp_words_path, exp_hex_path, expected_words);

    $display("TB_INFO: VGG16-like 32x32 P128 KV260 smoke-top AXI simulation");
    $display("TB_INFO: IFM_HEX=%s", ifm_hex_path);
    $display("TB_INFO: WGT_HEX=%s", wgt_hex_path);
    $display("TB_INFO: EXP_HEX=%s", exp_hex_path);
    $display("TB_INFO: expected_words=%0d", expected_words);
    $display("TB_INFO: DDR_WORD_W=%0d AXI_DATA_W=%0d WORD_BYTES=%0d", DDR_WORD_W, AXI_DATA_W, DDR_WORD_BYTES);
    $display("TB_INFO: AXI strict mode: direct/debug DDR writes are monitored but not mirrored into DDR.");
    $display("TB_INFO: MAX_CYCLES=%0d", MAX_CYCLES);

    // Initialize external DDR model.
    for (int i = 0; i < DDR_DEPTH; i++) begin
      ddr_mem[i] = '0;
    end
    for (int i = 0; i < OFM_MAX_WORDS; i++) begin
      exp_mem[i] = '0;
    end

    $readmemh(ifm_hex_path, ddr_mem, `DDR_IFM_BASE);
    $readmemh(wgt_hex_path, ddr_mem, `DDR_WGT_BASE);
    $readmemh(exp_hex_path, exp_mem);

    // Explicitly clear OFM region, matching board flow.
    for (int i = 0; i < `DDR_OFM_SIZE; i++) begin
      ddr_mem[`DDR_OFM_BASE + i] = '0;
    end

    rst_n        = 1'b0;
    soft_reset_n = 1'b0;
    run          = 1'b0;
    abort        = 1'b0;

    repeat (20) @(posedge clk);
    rst_n        = 1'b1;
    repeat (10) @(posedge clk);
    soft_reset_n = 1'b1;

    $display("TB_INFO: waiting for fixed-config loader cfg_done...");
    wait (cfg_done === 1'b1);
    $display("TB_INFO: cfg_done at t=%0t", $time);

    repeat (5) @(posedge clk);
    run = 1'b1;
    $display("TB_INFO: run asserted at t=%0t", $time);

    for (int cyc = 0; cyc < MAX_CYCLES; cyc++) begin
      @(posedge clk);
      if ((cyc % 50000) == 0) begin
        $display("TB_PROGRESS: cyc=%0d layer=%0d mode=%0d core_busy=%0b core_done=%0b err=%0b bridge_busy=%0b rd_req=%0b wr_en=%0b", cyc, dbg_layer_idx, dbg_mode, core_busy, core_done, error, bridge_busy, dbg_ddr_rd_req, dbg_ddr_wr_en);
      end
      if (error) begin
        $fatal(1, "TB_FAIL: DUT error at cyc=%0d layer=%0d mode=%0d dbg_error_vec=0x%0h core_error=%0b bridge_error=%0b fifo_ovf=%0b", cyc, dbg_layer_idx, dbg_mode, dbg_error_vec, core_error, bridge_error, wr_fifo_overflow);
      end
      if (done) begin
        $display("TB_INFO: done asserted at cyc=%0d t=%0t", cyc, $time);
        break;
      end
      if (cyc == MAX_CYCLES-1) begin
        $fatal(1, "TB_FAIL: timeout after %0d cycles. layer=%0d mode=%0d busy=%0b done=%0b error=%0b", MAX_CYCLES, dbg_layer_idx, dbg_mode, busy, done, error);
      end
    end

    // Wait a few cycles for any outstanding AXI write response / bridge drain.
    for (int drain = 0; drain < 10000; drain++) begin
      @(posedge clk);
      if (!bridge_busy && !m_axi_bvalid && !m_axi_rvalid) begin
        break;
      end
    end

    $display("TB_INFO: AXI channel counts AW=%0d W=%0d B=%0d AR=%0d R=%0d",
             axi_aw_count, axi_w_count, axi_b_count, axi_ar_count, axi_r_count);
    $display("TB_INFO: AXI writes total=%0d OFM=%0d first_ofm=0x%0h last_ofm=0x%0h",
             axi_write_count, axi_ofm_write_count, axi_first_ofm_wr_idx, axi_last_ofm_wr_idx);
    $display("TB_INFO: DBG writes total=%0d OFM=%0d first_any=0x%0h last_any=0x%0h first_ofm=0x%0h last_ofm=0x%0h",
             dbg_write_count, dbg_ofm_write_count, dbg_first_wr_idx, dbg_last_wr_idx,
             dbg_first_ofm_wr_idx, dbg_last_ofm_wr_idx);
    for (int s = 0; s < 16; s++) begin
      if (s < dbg_sample_count) begin
        $display("TB_DBG_WRITE_SAMPLE[%0d]: addr=0x%0h data=0x%0h be=0x%0h",
                 s, dbg_sample_addr[s], dbg_sample_data[s], dbg_sample_be[s]);
      end
    end
    $display("TB_INFO: BRIDGE_IN writes total=%0d first=0x%0h last=0x%0h",
             bridge_in_write_count, bridge_in_first_wr_idx, bridge_in_last_wr_idx);
    for (int s = 0; s < 16; s++) begin
      if (s < bridge_in_sample_count) begin
        $display("TB_BRIDGE_IN_SAMPLE[%0d]: addr=0x%0h data=0x%0h be=0x%0h",
                 s, bridge_in_sample_addr[s], bridge_in_sample_data[s], bridge_in_sample_be[s]);
      end
    end
    $display("TB_INFO: BRIDGE_INTERNAL wr_count=%0d wr_head=%0d wr_tail=%0d wr_issue_active=%0b wr_aw_sent=%0b wr_w_sent=%0b wr_outstanding=%0d",
             dut.u_top.u_dma_to_axi_bridge.wr_count_q,
             dut.u_top.u_dma_to_axi_bridge.wr_head_q,
             dut.u_top.u_dma_to_axi_bridge.wr_tail_q,
             dut.u_top.u_dma_to_axi_bridge.wr_issue_active_q,
             dut.u_top.u_dma_to_axi_bridge.wr_aw_sent_q,
             dut.u_top.u_dma_to_axi_bridge.wr_w_sent_q,
             dut.u_top.u_dma_to_axi_bridge.wr_outstanding_q);
    $display("TB_INFO: final bridge/core status bridge_busy=%0b awvalid=%0b wvalid=%0b bvalid=%0b arvalid=%0b rvalid=%0b wr_fifo_overflow=%0b bridge_error=%0b core_error=%0b",
             bridge_busy, m_axi_awvalid, m_axi_wvalid, m_axi_bvalid, m_axi_arvalid, m_axi_rvalid,
             wr_fifo_overflow, bridge_error, core_error);

    if (axi_ofm_write_count == 0) begin
      $display("TB_ERROR: strict AXI mode: no AXI writes reached DDR_OFM_BASE region 0x%0h..0x%0h.",
               `DDR_OFM_BASE, (`DDR_OFM_BASE + `DDR_OFM_SIZE - 1));
      $display("TB_ERROR: Direct DBG writes may still exist, but they are not mirrored into DDR in this testbench.");
    end

    out_fd = $fopen(out_hex_path, "w");
    if (out_fd == 0) begin
      $display("TB_WARN: cannot open OUT_HEX=%s for writing", out_hex_path);
    end

    mismatch_count = 0;
    for (int i = 0; i < expected_words; i++) begin
      logic [DDR_WORD_W-1:0] got;
      logic [DDR_WORD_W-1:0] exp;
      got = ddr_mem[`DDR_OFM_BASE + i];
      exp = exp_mem[i];
      if (out_fd != 0) begin
        $fdisplay(out_fd, "%0h", got);
      end
      if (got !== exp) begin
        if (mismatch_count < 32) begin
          $display("TB_MISMATCH_FINAL word=%0d got=0x%0h exp=0x%0h", i, got, exp);
        end
        mismatch_count++;
      end
    end
    if (out_fd != 0) begin
      $fclose(out_fd);
      $display("TB_INFO: wrote simulated OFM readback to %s", out_hex_path);
    end

    if (mismatch_count == 0) begin
      $display("TB_PASS: VGG16-like 32x32 P128 smoke-top output matched golden. words=%0d", expected_words);
    end else begin
      $fatal(1, "TB_FAIL: final OFM mismatch_count=%0d / words=%0d", mismatch_count, expected_words);
    end

    repeat (20) @(posedge clk);
    $finish;
  end

endmodule
