# Auto-generated by gen_kv260_9layer_ddr_images.py
# Load DDR images for the 9-layer Mode-1 DCP/EfficientNet-B0-prefix test.
#
# Use after psu_init/psu_post_config and after programming the bitstream.
# Prefer the PSU target to avoid A53 cache effects.
#
# Current target number can change across sessions. If target 5 is your PSU,
# "targets -set 5" is also OK. The filter below is usually safer.

targets
catch { targets -set -filter {name =~ "PSU"} }

set IFM_PHYS 0x70000000
set WGT_PHYS 0x70400000
set OFM_PHYS 0x70800000

puts "Loading IFM image to $IFM_PHYS ..."
dow -data {D:/sdh/CNN_V4/kv260_9layer_ddr_images/ifm_l0.bin} $IFM_PHYS

puts "Loading 9-layer weight image to $WGT_PHYS ..."
dow -data {D:/sdh/CNN_V4/kv260_9layer_ddr_images/weights_9layer.bin} $WGT_PHYS

puts "Clearing OFM region at $OFM_PHYS ..."
dow -data {D:/sdh/CNN_V4/kv260_9layer_ddr_images/ofm_zero.bin} $OFM_PHYS

puts "Verify IFM first 16 x 32-bit words:"
mrd $IFM_PHYS 16

puts "Verify WGT first 16 x 32-bit words:"
mrd $WGT_PHYS 16

puts "Verify OFM first 16 x 32-bit words should be zero:"
mrd $OFM_PHYS 16

puts "DDR load complete."
puts "Now use VIO: soft_reset_n=0, run=0, abort=0; then soft_reset_n=1; wait cfg_done=1; pulse run."
