`timescale 1ns/1ps
`include "cnn_ddr_defs.svh"

// Thin benchmark-specific wrapper. Set this as the Vivado top module.
module kv260_cnn_smoke_top_vgg16_like_96_p256
  import cnn_layer_desc_pkg::*;
#(
  parameter int DATA_W = 8,
  parameter int PSUM_W = 32,
  parameter int PTOTAL = 256,
  parameter int PV_MAX = 16,
  parameter int PF_MAX = 16,
  parameter int PC_MODE2 = 16,
  parameter int PF_MODE2 = 16,
  parameter int C_MAX = 128,
  parameter int F_MAX = 128,
  parameter int W_MAX = 96,
  parameter int H_MAX = 96,
  parameter int HT = 3,
  parameter int K_MAX = 3,
  parameter int OFM_ROW_STRIDE = 16,
  parameter int WGT_DEPTH = 4096,
  parameter int OFM_BANK_DEPTH = H_MAX * OFM_ROW_STRIDE,
  parameter int OFM_LINEAR_DEPTH = C_MAX * OFM_BANK_DEPTH,
  parameter int CFG_DEPTH = 16,
  parameter int DDR_ADDR_W = `CNN_DDR_ADDR_W,
  parameter int DDR_WORD_W = PV_MAX * DATA_W,
  parameter int AXI_ADDR_W = 40,
  parameter int AXI_DATA_W = DDR_WORD_W,
  parameter int AXI_ID_W = 1,
  parameter logic [AXI_ADDR_W-1:0] AXI_DDR_BASE_ADDR = 40'h0000_7000_0000,
  parameter int WR_FIFO_DEPTH = 64
)(
  input  logic clk,
  input  logic rst_n,
  input  logic soft_reset_n,
  input  logic run,
  input  logic abort,

  output logic cfg_done,
  output logic start_pulse,
  output logic busy,
  output logic done,
  output logic error,
  output logic core_busy,
  output logic core_done,
  output logic core_error,
  output logic bridge_busy,
  output logic bridge_error,
  output logic wr_fifo_overflow,
  output logic [$clog2(CFG_DEPTH)-1:0] dbg_layer_idx,
  output logic dbg_mode,
  output logic dbg_weight_bank,
  output logic [3:0] dbg_error_vec,

  output logic dbg_ddr_rd_req,
  output logic [DDR_ADDR_W-1:0] dbg_ddr_rd_addr,
  output logic dbg_ddr_rd_valid,
  output logic [DDR_WORD_W-1:0] dbg_ddr_rd_data,
  output logic dbg_ddr_wr_en,
  output logic [DDR_ADDR_W-1:0] dbg_ddr_wr_addr,
  output logic [DDR_WORD_W-1:0] dbg_ddr_wr_data,
  output logic [(DDR_WORD_W/8)-1:0] dbg_ddr_wr_be,

  output logic [AXI_ID_W-1:0] m_axi_awid,
  output logic [AXI_ADDR_W-1:0] m_axi_awaddr,
  output logic [7:0] m_axi_awlen,
  output logic [2:0] m_axi_awsize,
  output logic [1:0] m_axi_awburst,
  output logic m_axi_awlock,
  output logic [3:0] m_axi_awcache,
  output logic [2:0] m_axi_awprot,
  output logic [3:0] m_axi_awqos,
  output logic [3:0] m_axi_awregion,
  output logic m_axi_awvalid,
  input  logic m_axi_awready,

  output logic [AXI_DATA_W-1:0] m_axi_wdata,
  output logic [(AXI_DATA_W/8)-1:0] m_axi_wstrb,
  output logic m_axi_wlast,
  output logic m_axi_wvalid,
  input  logic m_axi_wready,

  input  logic [AXI_ID_W-1:0] m_axi_bid,
  input  logic [1:0] m_axi_bresp,
  input  logic m_axi_bvalid,
  output logic m_axi_bready,

  output logic [AXI_ID_W-1:0] m_axi_arid,
  output logic [AXI_ADDR_W-1:0] m_axi_araddr,
  output logic [7:0] m_axi_arlen,
  output logic [2:0] m_axi_arsize,
  output logic [1:0] m_axi_arburst,
  output logic m_axi_arlock,
  output logic [3:0] m_axi_arcache,
  output logic [2:0] m_axi_arprot,
  output logic [3:0] m_axi_arqos,
  output logic [3:0] m_axi_arregion,
  output logic m_axi_arvalid,
  input  logic m_axi_arready,

  input  logic [AXI_ID_W-1:0] m_axi_rid,
  input  logic [AXI_DATA_W-1:0] m_axi_rdata,
  input  logic [1:0] m_axi_rresp,
  input  logic m_axi_rlast,
  input  logic m_axi_rvalid,
  output logic m_axi_rready
);

  kv260_cnn_eval_top_pkgcfg_vgg16_like_96_p256_defaults #(
    .DATA_W(DATA_W),
    .PSUM_W(PSUM_W),
    .PTOTAL(PTOTAL),
    .PV_MAX(PV_MAX),
    .PF_MAX(PF_MAX),
    .PC_MODE2(PC_MODE2),
    .PF_MODE2(PF_MODE2),
    .C_MAX(C_MAX),
    .F_MAX(F_MAX),
    .W_MAX(W_MAX),
    .H_MAX(H_MAX),
    .HT(HT),
    .K_MAX(K_MAX),
    .OFM_ROW_STRIDE(OFM_ROW_STRIDE),
    .WGT_DEPTH(WGT_DEPTH),
    .OFM_BANK_DEPTH(OFM_BANK_DEPTH),
    .OFM_LINEAR_DEPTH(OFM_LINEAR_DEPTH),
    .CFG_DEPTH(CFG_DEPTH),
    .DDR_ADDR_W(DDR_ADDR_W),
    .DDR_WORD_W(DDR_WORD_W),
    .AXI_ADDR_W(AXI_ADDR_W),
    .AXI_DATA_W(AXI_DATA_W),
    .AXI_ID_W(AXI_ID_W),
    .AXI_DDR_BASE_ADDR(AXI_DDR_BASE_ADDR),
    .WR_FIFO_DEPTH(WR_FIFO_DEPTH)
  ) u_top (
    .*
  );

endmodule
