package cnn_layer_desc_pkg;
// Auto-generated by layer_csv_to_layer_pkg.py
// Source CSV: eval\configs\vgg16_like_96_p256_layers_with_wgt_base.csv
// RTL mode convention: MODE1=0, MODE2=1

localparam int DIM_W      = 8;
localparam int K_W        = 4;
localparam int PV_W       = 8;
localparam int PF1_W      = 8;
localparam int PC2_W      = 8;
localparam int PF2_W      = 8;
localparam int ADDR_W     = 32;
localparam int STRIDE_W   = 2;
localparam int PAD_W      = 4;
localparam int POOL_W     = 2;
localparam int LAYER_ID_W = 8;

localparam int NUM_LAYERS = 13;

typedef enum logic [0:0] {
  MODE1 = 1'b0,
  MODE2 = 1'b1
} layer_mode_e;

typedef struct packed {
  logic [LAYER_ID_W-1:0] layer_id;
  layer_mode_e mode;

  logic [DIM_W-1:0] h_in;
  logic [DIM_W-1:0] w_in;
  logic [DIM_W-1:0] c_in;
  logic [DIM_W-1:0] f_out;
  logic [K_W-1:0]   k;
  logic [DIM_W-1:0] h_out;
  logic [DIM_W-1:0] w_out;

  logic [PV_W-1:0]  pv_m1;
  logic [PF1_W-1:0] pf_m1;
  logic [PC2_W-1:0] pc_m2;
  logic [PF2_W-1:0] pf_m2;

  logic [STRIDE_W-1:0] conv_stride;
  logic [PAD_W-1:0]    pad_top;
  logic [PAD_W-1:0]    pad_bottom;
  logic [PAD_W-1:0]    pad_left;
  logic [PAD_W-1:0]    pad_right;
  logic                relu_en;
  logic                pool_en;
  logic [POOL_W-1:0]   pool_k;
  logic [POOL_W-1:0]   pool_stride;

  logic [ADDR_W-1:0] ifm_ddr_base;
  logic [ADDR_W-1:0] wgt_ddr_base;
  logic [ADDR_W-1:0] ofm_ddr_base;

  logic first_layer;
  logic last_layer;
} layer_desc_t;

function automatic layer_desc_t get_layer_desc(input int unsigned idx);
  begin
    get_layer_desc = '0;
    unique case (idx)
      0: get_layer_desc = '{
      layer_id     : 8'd0,
      mode         : MODE1,
      h_in         : 8'd96,
      w_in         : 8'd96,
      c_in         : 8'd3,
      f_out        : 8'd16,
      k            : 4'd3,
      h_out        : 8'd96,
      w_out        : 8'd96,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00010000,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b1,
      last_layer   : 1'b0
    };
      1: get_layer_desc = '{
      layer_id     : 8'd1,
      mode         : MODE1,
      h_in         : 8'd96,
      w_in         : 8'd96,
      c_in         : 8'd16,
      f_out        : 8'd16,
      k            : 4'd3,
      h_out        : 8'd96,
      w_out        : 8'd96,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b1,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00010020,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      2: get_layer_desc = '{
      layer_id     : 8'd2,
      mode         : MODE1,
      h_in         : 8'd48,
      w_in         : 8'd48,
      c_in         : 8'd16,
      f_out        : 8'd32,
      k            : 4'd3,
      h_out        : 8'd48,
      w_out        : 8'd48,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h000100B0,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      3: get_layer_desc = '{
      layer_id     : 8'd3,
      mode         : MODE1,
      h_in         : 8'd48,
      w_in         : 8'd48,
      c_in         : 8'd32,
      f_out        : 8'd32,
      k            : 4'd3,
      h_out        : 8'd48,
      w_out        : 8'd48,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b1,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h000101D0,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      4: get_layer_desc = '{
      layer_id     : 8'd4,
      mode         : MODE1,
      h_in         : 8'd24,
      w_in         : 8'd24,
      c_in         : 8'd32,
      f_out        : 8'd64,
      k            : 4'd3,
      h_out        : 8'd24,
      w_out        : 8'd24,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00010410,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      5: get_layer_desc = '{
      layer_id     : 8'd5,
      mode         : MODE1,
      h_in         : 8'd24,
      w_in         : 8'd24,
      c_in         : 8'd64,
      f_out        : 8'd64,
      k            : 4'd3,
      h_out        : 8'd24,
      w_out        : 8'd24,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00010890,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      6: get_layer_desc = '{
      layer_id     : 8'd6,
      mode         : MODE1,
      h_in         : 8'd24,
      w_in         : 8'd24,
      c_in         : 8'd64,
      f_out        : 8'd64,
      k            : 4'd3,
      h_out        : 8'd24,
      w_out        : 8'd24,
      pv_m1        : 8'd16,
      pf_m1        : 8'd16,
      pc_m2        : 8'd0,
      pf_m2        : 8'd0,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b1,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00011190,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      7: get_layer_desc = '{
      layer_id     : 8'd7,
      mode         : MODE2,
      h_in         : 8'd12,
      w_in         : 8'd12,
      c_in         : 8'd64,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd12,
      w_out        : 8'd12,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00011A90,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      8: get_layer_desc = '{
      layer_id     : 8'd8,
      mode         : MODE2,
      h_in         : 8'd12,
      w_in         : 8'd12,
      c_in         : 8'd128,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd12,
      w_out        : 8'd12,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00012C90,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      9: get_layer_desc = '{
      layer_id     : 8'd9,
      mode         : MODE2,
      h_in         : 8'd12,
      w_in         : 8'd12,
      c_in         : 8'd128,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd12,
      w_out        : 8'd12,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b1,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00015090,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      10: get_layer_desc = '{
      layer_id     : 8'd10,
      mode         : MODE2,
      h_in         : 8'd6,
      w_in         : 8'd6,
      c_in         : 8'd128,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd6,
      w_out        : 8'd6,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00017490,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      11: get_layer_desc = '{
      layer_id     : 8'd11,
      mode         : MODE2,
      h_in         : 8'd6,
      w_in         : 8'd6,
      c_in         : 8'd128,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd6,
      w_out        : 8'd6,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b0,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h00019890,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b0
    };
      12: get_layer_desc = '{
      layer_id     : 8'd12,
      mode         : MODE2,
      h_in         : 8'd6,
      w_in         : 8'd6,
      c_in         : 8'd128,
      f_out        : 8'd128,
      k            : 4'd3,
      h_out        : 8'd6,
      w_out        : 8'd6,
      pv_m1        : 8'd0,
      pf_m1        : 8'd0,
      pc_m2        : 8'd16,
      pf_m2        : 8'd16,
      conv_stride  : 2'd1,
      pad_top      : 4'd1,
      pad_bottom   : 4'd1,
      pad_left     : 4'd1,
      pad_right    : 4'd1,
      relu_en      : 1'b1,
      pool_en      : 1'b1,
      pool_k       : 2'd2,
      pool_stride  : 2'd2,
      ifm_ddr_base : 32'h00000000,
      wgt_ddr_base : 32'h0001BC90,
      ofm_ddr_base : 32'h00020000,
      first_layer  : 1'b0,
      last_layer   : 1'b1
    };
      default: get_layer_desc = '0;
    endcase
  end
endfunction

endpackage
